apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: distributed-web-app
type: Opaque
stringData:
  mysql-root-password: root
  rabbitmq-user: admin
  rabbitmq-password: admin
  keycloak-admin: admin
  keycloak-admin-password: admin
