server.port=8081

spring.application.name=PRODUCT-SERVICE

spring.datasource.url=jdbc:mysql://127.0.0.1:13307/productdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect